[package]
name = "generic-actor"
version = "0.1.0"
authors = ["ben-glaeser <ben.glaeser@aperto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8.3"
futures = "0.1.28"
rand = "0.7.0"
